#!/bin/bash
#jvfx.sh

fileName=$1

if [ -z $1 ]; then
     echo "JavaFX - cannot run JavaFx without arguments
    Usage: jvfx [arg]"
else
    java --module-path /Users/rggarcia/Documents/javafx-sdk-14/lib/ --add-modules javafx.controls $fileName
fi

