#!/bin/bash
#mkctmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

header_file="$file_name.h"
c_impl_file="$file_name.c"
files=($header_file $c_impl_file)

if [ -f ./$header_file ] || [ -f ./$c_impl_file ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

# header file
CAPITALIZED_HEADER="`echo "${file_name}" | tr '[:lower:]' '[:upper:]'`_H"

echo "/* Program Name: $header_file
 * Date: `date +'%b %d, %Y'`
 */

#ifndef $CAPITALIZED_HEADER
#define $CAPITALIZED_HEADER

#endif
" > $header_file

 # c implementation file
echo "/* Program Name: $c_impl_file
 * Date: `date +'%b %d, %Y'`
 */

#include "\"$header_file\""
" > $c_impl_file

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi -O  $header_file $c_impl_file
else
    exit 0
fi
