#!/bin/bash
#mkctmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

header_file="$file_name.hpp"
cpp_impl_file="$file_name.cpp"
files=($header_file $cpp_impl_file)

if [ -f ./$header_file ] || [ -f ./$cpp_impl_file ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

# header file
CAPITALIZED_HEADER="`echo "${file_name}" | tr '[:lower:]' '[:upper:]'`_H"
first_letter_capitalized="`echo "${file_name:0:1}" | tr '[:lower:]' '[:upper:]'`${file_name:1}"

echo "/* Program Name: $header_file
 * Purpose: 
 * Coder: Ramon Gnan Garcia - 0926596
 * Date: `date +'%b %d, %Y'`
 */

#ifndef $CAPITALIZED_HEADER
#define $CAPITALIZED_HEADER

class "$first_letter_capitalized"
{

};

#endif
" > $header_file

 # c implementation file
echo "/* Program Name: $cpp_impl_file
 * Purpose: 
 * Coder: Ramon Gnan Garcia - 0926596
 * Date: `date +'%b %d, %Y'`
 */

#include "\"$header_file\""

" > $cpp_impl_file

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi -O  $header_file $cpp_impl_file
else
    exit 0
fi
