#!/bin/bash
#mkcsinttmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.cs"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

namespace=`basename "$PWD"`
overwrite_namespace='n'
read -p "'$namespace' will be used as namespace name. Want to overwrite [y/N]? " overwrite_namespace

if [[ "$overwrite_namespace" = 'y' || "$overwrite_namespace" = 'Y' ]]; then
    read -p "namespace: " namespace
fi

#className=`echo ${file_name} | sed 's/.java//g'`
class_name=`basename $file_name .cs`

echo "/* Program Name: ${file_name}
 * Date: `date +'%b %d, %Y'`
 */

using System;

namespace $namespace
{
	public interface $class_name
	{

	}
}" > ${file_name}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi

