#!/bin/bash
#mkctmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.c"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

echo "/* Program Name: ${file_name}
 * Date: `date +'%b %d, %Y'`
 */

#include <stdio.h>

int main()
{

	return 0;

}" > ${file_name}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi
