#!/bin/bash
#mkhtmltmpl

file_name=$1
overwrite='n'
dqt='"'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.html"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

echo "<!DOCTYPE HTML>
<html>
	<head>
		<title></title>
		<meta charset=${dqt}UTF-8${dqt}>
		<link href=${dqt}main.css${dqt} rel=${dqt}stylesheet${dqt} />

		<!--[if lt IE 9]>
		<script src=${dqt}http://html5shiv.googlecode.com/svn/trunk/html5.js${dqt}></script>
		<![endif]-->
	</head>
	<body>
	</body>
</html>" > ${file_name}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi
