#!/bin/bash
#mkjstmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.js"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

echo "/* Program Name: ${file_name}
 * Purpose: 
 * Coder: Ramon Gnan Garcia - 0926596
 * Date: `date +'%b %d, %Y'`
 */


" > ${file_name}

tern_project_file=".tern-project"

if [ -f ./$tern_project_file ]; then
    exit 0
fi

echo "{
  "libs": [
    ],
  "loadEagerly": [
      "/Users/rggarcia/js/**/*.js"
    ],
  "plugins": {
      "requirejs": {
            "baseURL": "./",
            "paths": {}
          }
    }
}" > ${tern_project_file}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi
