#!/bin/bash
#mkjstmpl

tern_project_file=".tern-project"
dqt='"'

if [ ! -f ./$tern_project_file ]; then
    echo "{
    ${dqt}libs${dqt}: [
    ${dqt}browser${dqt},
    ${dqt}jquery${dqt},
    ${dqt}react${dqt}
  ],
  ${dqt}plugins${dqt}: {
      ${dqt}angular${dqt}: {},
      ${dqt}doc_comment${dqt}: null,
      ${dqt}es_modules${dqt}: {},
      ${dqt}node${dqt}: {}
  },
  ${dqt}dontLoad${dqt}: [
      ${dqt}node_modules/**${dqt}
  ]
}" > ${tern_project_file}
fi

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.js"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

echo "/* Program Name: ${file_name}
 * Date: `date +'%b %d, %Y'`
 */
" > ${file_name}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi
