#!/bin/bash
#mkjtmpl

file_name=$1
overwrite='n'

if [ -z $1 ]; then
    read -p "File name: " file_name
fi

file_name="${file_name}.java"

if [ -f ./$file_name ]; then
    read -p  "$file_name already exists! Overwrite? [y/N]? " overwrite

    if [[ "$overwrite" = 'n' || "$overwrite" = 'N' || -z $overwrite ]]; then
        exit 0
    fi
fi

#className=`echo ${file_name} | sed 's/.java//g'`
className=`basename $file_name .java`

echo "/* Program Name: ${file_name}
 * Purpose: 
 * Coder: Ramon Gnan Garcia - 0926596
 * Date: `date +'%b %d, %Y'`
 */

public class ${className}
{
    public static void main(String []args)
    {

    }//end of main

}//end of class" > ${file_name}

read -p "Open file? " open_file
if [[ "${open_file}" = 'y' || "${open_file}" = 'Y' ]]; then
    vi ${file_name}
else
    exit 0
fi

