#!/bin/bash
#mkternfile

tern_project_file=".tern-project"
dqt='"'

if [ ! -f ./$tern_project_file ]; then
    echo "{
    ${dqt}libs${dqt}: [
    ${dqt}browser${dqt},
    ${dqt}jquery${dqt},
    ${dqt}react${dqt}
  ],
  ${dqt}plugins${dqt}: {
      ${dqt}angular${dqt}: {},
      ${dqt}doc_comment${dqt}: null,
      ${dqt}es_modules${dqt}: {},
      ${dqt}node${dqt}: {}
  },
  ${dqt}dontLoad${dqt}: [
      ${dqt}node_modules/**${dqt}
  ]
}" > ${tern_project_file}
fi
